version: "3"
services:
    node8:
        image: "node:8"
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
            - PORT=8008
        ports:
            - "8008:8008"
        volumes:
            - ./:/home/node/app
        command: "npm start"

    node7:
        image: "node:7"
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
            - PORT=8007
        ports:
            - "8007:8007"
        volumes:
            - ./:/home/node/app
        command: "npm start"

    node6:
        image: "node:6"
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
            - PORT=8006
        ports:
            - "8006:8006"
        volumes:
            - ./:/home/node/app
        command: "npm start"
